In [1]:
import pandas as pd

In [2]:
# Method 1: Specify Full Path to File

In [4]:
#Windows:
stats = pd.read_csv('C:\\Users\\trungvb\\Desktop\\Mail3829 (8).csv')
#Mac:
#stats = pd.read_csv('/Users/trungvb/Desktop/Range_IPs.txt')

In [5]:
stats

,CTID,IP,CPU,Ram,Ram use,Disk,Disk use,Trang thai VM,Trang thai Disk,Trang thai Ram,Disk_vz
0,1287,103.28.38.164,2,3072,38%,89G,12%,running,OK,OK,/vz2/private/1287
1,1291,103.28.38.45,2,3072,41%,89G,11%,running,OK,OK,/vz2/private/1291
2,1293,103.28.38.80,2,3072,33%,128G,8%,running,OK,OK,/vz2/private/1293
3,1295,103.28.38.210,2,3072,36%,89G,26%,running,OK,OK,/vz2/private/1295
4,1296,103.28.38.216,2,3072,48%,89G,22%,running,OK,OK,/vz2/private/1296
5,1297,103.28.38.175,4,4096,25%,197G,8%,running,OK,OK,/vz3/private/1297
6,1298,103.28.38.155,2,3072,41%,128G,24%,running,OK,OK,/vz1/private/1298
7,1299,103.28.38.39,2,3072,32%,89G,12%,running,OK,OK,/vz1/private/1299
8,1300,103.28.38.83,4,6000,81%,256G,9%,running,OK,OK,/vz3/private/1300
9,1301,103.28.38.146,4,6000,93%,256G,10%,running,OK,FULL RAM,/vz3/private/1301
10,1302,103.28.38.174,2,3072,42%,89G,16%,running,OK,OK,/vz3/private/1302
11,1303,103.28.38.134,4,8000,85%,256G,7%,running,OK,OK,/vz4/private/1303
12,1304,103.28.38.202,2,3072,29%,89G,11%,running,OK,OK,/vz4/private/1304
13,1306,103.28.38.196,2,3000,44%,197G,7%,running,OK,OK,/vz4/private/1306
14,1307,103.28.38.215,2,3072,34%,89G,80%,running,OK,OK,/vz4/private/1307
15,1309,103.28.38.203,2,3072,52%,85G,38%,running,OK,OK,/vz5/private/1309
16,1312,103.28.38.211,2,3000,37%,79G,13%,running,OK,OK,/vz5/private/1312
17,1319,103.28.38.222,2,3072,41%,79G,15%,running,OK,OK,/vz6/private/1319
18,1320,103.28.38.212,4,8000,81%,207G,10%,running,OK,OK,/vz6/private/1320
19,1323,103.28.38.137,2,3000,52%,79G,23%,running,OK,OK,/vz6/private/1323
20,1402,103.28.38.224,2,3072,37%,89G,13%,running,OK,OK,/vz6/private/1402
21,1442,103.28.38.214,4,3000,38%,84G,10%,running,OK,OK,/vz1/private/1442
22,1443,103.28.38.21,2,3072,36%,89G,20%,running,OK,OK,/vz5/private/1443
23,1503,103.28.38.220,3,3072,64%,207G,31%,running,OK,OK,/vz2/private/1503
24,1533,103.28.38.180,2,3000,32%,84G,9%,running,OK,OK,/vz6/private/1533
25,1535,103.28.38.208,2,3000,27%,84G,9%,running,OK,OK,/vz6/private/1535
26,1636,103.28.38.163,2,3072,29%,89G,4%,running,OK,OK,/vz1/private/1636
27,1637,103.28.38.138,2,3072,34%,89G,5%,running,OK,OK,/vz1/private/1637

In [6]:
# Methd 2: Change Working Directory
import os

In [7]:
print(os.getcwd())

C:\Users\trungvb\Documents\GitHub\thuctap-NhanHoa\Python

In [9]:
# Windows:
os.chdir('C:\\Users\\trungvb\\Desktop')

In [10]:
print(os.getcwd())

C:\Users\trungvb\Desktop

In [11]:
stats2 = pd.read_csv('Mail3829 (8).csv')

In [12]:
stats2

,CTID,IP,CPU,Ram,Ram use,Disk,Disk use,Trang thai VM,Trang thai Disk,Trang thai Ram,Disk_vz
0,1287,103.28.38.164,2,3072,38%,89G,12%,running,OK,OK,/vz2/private/1287
1,1291,103.28.38.45,2,3072,41%,89G,11%,running,OK,OK,/vz2/private/1291
2,1293,103.28.38.80,2,3072,33%,128G,8%,running,OK,OK,/vz2/private/1293
3,1295,103.28.38.210,2,3072,36%,89G,26%,running,OK,OK,/vz2/private/1295
4,1296,103.28.38.216,2,3072,48%,89G,22%,running,OK,OK,/vz2/private/1296
5,1297,103.28.38.175,4,4096,25%,197G,8%,running,OK,OK,/vz3/private/1297
6,1298,103.28.38.155,2,3072,41%,128G,24%,running,OK,OK,/vz1/private/1298
7,1299,103.28.38.39,2,3072,32%,89G,12%,running,OK,OK,/vz1/private/1299
8,1300,103.28.38.83,4,6000,81%,256G,9%,running,OK,OK,/vz3/private/1300
9,1301,103.28.38.146,4,6000,93%,256G,10%,running,OK,FULL RAM,/vz3/private/1301
10,1302,103.28.38.174,2,3072,42%,89G,16%,running,OK,OK,/vz3/private/1302
11,1303,103.28.38.134,4,8000,85%,256G,7%,running,OK,OK,/vz4/private/1303
12,1304,103.28.38.202,2,3072,29%,89G,11%,running,OK,OK,/vz4/private/1304
13,1306,103.28.38.196,2,3000,44%,197G,7%,running,OK,OK,/vz4/private/1306
14,1307,103.28.38.215,2,3072,34%,89G,80%,running,OK,OK,/vz4/private/1307
15,1309,103.28.38.203,2,3072,52%,85G,38%,running,OK,OK,/vz5/private/1309
16,1312,103.28.38.211,2,3000,37%,79G,13%,running,OK,OK,/vz5/private/1312
17,1319,103.28.38.222,2,3072,41%,79G,15%,running,OK,OK,/vz6/private/1319
18,1320,103.28.38.212,4,8000,81%,207G,10%,running,OK,OK,/vz6/private/1320
19,1323,103.28.38.137,2,3000,52%,79G,23%,running,OK,OK,/vz6/private/1323
20,1402,103.28.38.224,2,3072,37%,89G,13%,running,OK,OK,/vz6/private/1402
21,1442,103.28.38.214,4,3000,38%,84G,10%,running,OK,OK,/vz1/private/1442
22,1443,103.28.38.21,2,3072,36%,89G,20%,running,OK,OK,/vz5/private/1443
23,1503,103.28.38.220,3,3072,64%,207G,31%,running,OK,OK,/vz2/private/1503
24,1533,103.28.38.180,2,3000,32%,84G,9%,running,OK,OK,/vz6/private/1533
25,1535,103.28.38.208,2,3000,27%,84G,9%,running,OK,OK,/vz6/private/1535
26,1636,103.28.38.163,2,3072,29%,89G,4%,running,OK,OK,/vz1/private/1636
27,1637,103.28.38.138,2,3072,34%,89G,5%,running,OK,OK,/vz1/private/1637

In [14]:
# 2. Number of rows
len(stats)  #28 rows imported

28

In [15]:
# 3. See columns
stats.columns

Index(['CTID', ' IP', ' CPU', ' Ram', ' Ram use', ' Disk', ' Disk use',
       ' Trang thai VM', ' Trang thai Disk', ' Trang thai Ram', ' Disk_vz'],
      dtype='object')

In [16]:
# 4. Number of columns
len(stats.columns)

11

In [19]:
# 5. Top rows
stats.head()

,CTID,IP,CPU,Ram,Ram use,Disk,Disk use,Trang thai VM,Trang thai Disk,Trang thai Ram,Disk_vz
0,1287,103.28.38.164,2,3072,38%,89G,12%,running,OK,OK,/vz2/private/1287
1,1291,103.28.38.45,2,3072,41%,89G,11%,running,OK,OK,/vz2/private/1291
2,1293,103.28.38.80,2,3072,33%,128G,8%,running,OK,OK,/vz2/private/1293
3,1295,103.28.38.210,2,3072,36%,89G,26%,running,OK,OK,/vz2/private/1295
4,1296,103.28.38.216,2,3072,48%,89G,22%,running,OK,OK,/vz2/private/1296

In [20]:
stats.head(7)

,CTID,IP,CPU,Ram,Ram use,Disk,Disk use,Trang thai VM,Trang thai Disk,Trang thai Ram,Disk_vz
0,1287,103.28.38.164,2,3072,38%,89G,12%,running,OK,OK,/vz2/private/1287
1,1291,103.28.38.45,2,3072,41%,89G,11%,running,OK,OK,/vz2/private/1291
2,1293,103.28.38.80,2,3072,33%,128G,8%,running,OK,OK,/vz2/private/1293
3,1295,103.28.38.210,2,3072,36%,89G,26%,running,OK,OK,/vz2/private/1295
4,1296,103.28.38.216,2,3072,48%,89G,22%,running,OK,OK,/vz2/private/1296
5,1297,103.28.38.175,4,4096,25%,197G,8%,running,OK,OK,/vz3/private/1297
6,1298,103.28.38.155,2,3072,41%,128G,24%,running,OK,OK,/vz1/private/1298

In [21]:
# 6. Bottom rows
stats.tail(6)

,CTID,IP,CPU,Ram,Ram use,Disk,Disk use,Trang thai VM,Trang thai Disk,Trang thai Ram,Disk_vz
22,1443,103.28.38.21,2,3072,36%,89G,20%,running,OK,OK,/vz5/private/1443
23,1503,103.28.38.220,3,3072,64%,207G,31%,running,OK,OK,/vz2/private/1503
24,1533,103.28.38.180,2,3000,32%,84G,9%,running,OK,OK,/vz6/private/1533
25,1535,103.28.38.208,2,3000,27%,84G,9%,running,OK,OK,/vz6/private/1535
26,1636,103.28.38.163,2,3072,29%,89G,4%,running,OK,OK,/vz1/private/1636
27,1637,103.28.38.138,2,3072,34%,89G,5%,running,OK,OK,/vz1/private/1637

In [22]:
# 7. Information on the columns
stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CTID              28 non-null     int64
 1    IP               28 non-null     object
 2    CPU              28 non-null     int64
 3    Ram              28 non-null     int64
 4    Ram use          28 non-null     object
 5    Disk             28 non-null     object
 6    Disk use         28 non-null     object
 7    Trang thai VM    28 non-null     object
 8    Trang thai Disk  28 non-null     object
 9    Trang thai Ram   28 non-null     object
 10   Disk_vz          28 non-null     object
dtypes: int64(3), object(8)
memory usage: 2.5+ KB

In [23]:
# 8. Get stats on the columns
stats.describe()

              CTID        CPU          Ram
count    28.000000  28.000000    28.000000
mean   1364.035714   2.464286  3654.285714
std     108.076270   0.838082  1456.820863
min    1287.000000   2.000000  3000.000000
25%    1298.750000   2.000000  3072.000000
50%    1306.500000   2.000000  3072.000000
75%    1412.000000   2.250000  3072.000000
max    1637.000000   4.000000  8000.000000

In [26]:
stats.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
CTID,28.0,1364.035714,108.076270,1287.0,1298.75,1306.5,1412.00,1637.0
CPU,28.0,2.464286,0.838082,2.0,2.00,2.0,2.25,4.0
Ram,28.0,3654.285714,1456.820863,3000.0,3072.00,3072.0,3072.00,8000.0

---

In [27]:
## Renaming Columns of a Dataframe

In [28]:
stats.head()

,CTID,IP,CPU,Ram,Ram use,Disk,Disk use,Trang thai VM,Trang thai Disk,Trang thai Ram,Disk_vz
0,1287,103.28.38.164,2,3072,38%,89G,12%,running,OK,OK,/vz2/private/1287
1,1291,103.28.38.45,2,3072,41%,89G,11%,running,OK,OK,/vz2/private/1291
2,1293,103.28.38.80,2,3072,33%,128G,8%,running,OK,OK,/vz2/private/1293
3,1295,103.28.38.210,2,3072,36%,89G,26%,running,OK,OK,/vz2/private/1295
4,1296,103.28.38.216,2,3072,48%,89G,22%,running,OK,OK,/vz2/private/1296

In [29]:
stats.columns

Index(['CTID', ' IP', ' CPU', ' Ram', ' Ram use', ' Disk', ' Disk use',
       ' Trang thai VM', ' Trang thai Disk', ' Trang thai Ram', ' Disk_vz'],
      dtype='object')

In [30]:
stats.columns = ['a','b','c','d','e','f','g','h','i','j','k']

In [31]:
stats.columns

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k'], dtype='object')

In [32]:
stats.head()

,a,b,c,d,e,f,g,h,i,j,k
0,1287,103.28.38.164,2,3072,38%,89G,12%,running,OK,OK,/vz2/private/1287
1,1291,103.28.38.45,2,3072,41%,89G,11%,running,OK,OK,/vz2/private/1291
2,1293,103.28.38.80,2,3072,33%,128G,8%,running,OK,OK,/vz2/private/1293
3,1295,103.28.38.210,2,3072,36%,89G,26%,running,OK,OK,/vz2/private/1295
4,1296,103.28.38.216,2,3072,48%,89G,22%,running,OK,OK,/vz2/private/1296

In [52]:
stats.columns = ['CTID', 'IP', 'CPU', 'Ram', 'Ram use', 'Disk', 'Disk use',
       'Trang thai VM', 'Trang thai Disk', 'Trang thai Ram', 'Disk_vz']

---

In [34]:
### Subsetting dataframes in Pandas

In [35]:
stats.head()

,CTID,IP,CPU,Ram,Ram use,Disk,Disk use,Trang thai VM,Trang thai Disk,Trang thai Ram,Disk_vz
0,1287,103.28.38.164,2,3072,38%,89G,12%,running,OK,OK,/vz2/private/1287
1,1291,103.28.38.45,2,3072,41%,89G,11%,running,OK,OK,/vz2/private/1291
2,1293,103.28.38.80,2,3072,33%,128G,8%,running,OK,OK,/vz2/private/1293
3,1295,103.28.38.210,2,3072,36%,89G,26%,running,OK,OK,/vz2/private/1295
4,1296,103.28.38.216,2,3072,48%,89G,22%,running,OK,OK,/vz2/private/1296

In [36]:
# 3 parts:
# - Rows
# - Columns
# - Combine the two

In [39]:
# Part 1: Rows
stats[2:6]

,CTID,IP,CPU,Ram,Ram use,Disk,Disk use,Trang thai VM,Trang thai Disk,Trang thai Ram,Disk_vz
2,1293,103.28.38.80,2,3072,33%,128G,8%,running,OK,OK,/vz2/private/1293
3,1295,103.28.38.210,2,3072,36%,89G,26%,running,OK,OK,/vz2/private/1295
4,1296,103.28.38.216,2,3072,48%,89G,22%,running,OK,OK,/vz2/private/1296
5,1297,103.28.38.175,4,4096,25%,197G,8%,running,OK,OK,/vz3/private/1297

In [41]:
stats[10:]

,CTID,IP,CPU,Ram,Ram use,Disk,Disk use,Trang thai VM,Trang thai Disk,Trang thai Ram,Disk_vz
10,1302,103.28.38.174,2,3072,42%,89G,16%,running,OK,OK,/vz3/private/1302
11,1303,103.28.38.134,4,8000,85%,256G,7%,running,OK,OK,/vz4/private/1303
12,1304,103.28.38.202,2,3072,29%,89G,11%,running,OK,OK,/vz4/private/1304
13,1306,103.28.38.196,2,3000,44%,197G,7%,running,OK,OK,/vz4/private/1306
14,1307,103.28.38.215,2,3072,34%,89G,80%,running,OK,OK,/vz4/private/1307
15,1309,103.28.38.203,2,3072,52%,85G,38%,running,OK,OK,/vz5/private/1309
16,1312,103.28.38.211,2,3000,37%,79G,13%,running,OK,OK,/vz5/private/1312
17,1319,103.28.38.222,2,3072,41%,79G,15%,running,OK,OK,/vz6/private/1319
18,1320,103.28.38.212,4,8000,81%,207G,10%,running,OK,OK,/vz6/private/1320
19,1323,103.28.38.137,2,3000,52%,79G,23%,running,OK,OK,/vz6/private/1323
20,1402,103.28.38.224,2,3072,37%,89G,13%,running,OK,OK,/vz6/private/1402
21,1442,103.28.38.214,4,3000,38%,84G,10%,running,OK,OK,/vz1/private/1442
22,1443,103.28.38.21,2,3072,36%,89G,20%,running,OK,OK,/vz5/private/1443
23,1503,103.28.38.220,3,3072,64%,207G,31%,running,OK,OK,/vz2/private/1503
24,1533,103.28.38.180,2,3000,32%,84G,9%,running,OK,OK,/vz6/private/1533
25,1535,103.28.38.208,2,3000,27%,84G,9%,running,OK,OK,/vz6/private/1535
26,1636,103.28.38.163,2,3072,29%,89G,4%,running,OK,OK,/vz1/private/1636
27,1637,103.28.38.138,2,3072,34%,89G,5%,running,OK,OK,/vz1/private/1637

In [42]:
stats[:5]

,CTID,IP,CPU,Ram,Ram use,Disk,Disk use,Trang thai VM,Trang thai Disk,Trang thai Ram,Disk_vz
0,1287,103.28.38.164,2,3072,38%,89G,12%,running,OK,OK,/vz2/private/1287
1,1291,103.28.38.45,2,3072,41%,89G,11%,running,OK,OK,/vz2/private/1291
2,1293,103.28.38.80,2,3072,33%,128G,8%,running,OK,OK,/vz2/private/1293
3,1295,103.28.38.210,2,3072,36%,89G,26%,running,OK,OK,/vz2/private/1295
4,1296,103.28.38.216,2,3072,48%,89G,22%,running,OK,OK,/vz2/private/1296

In [43]:
# Quick exercise (refresher)
# Reverse the dataframe
stats[::-1]

,CTID,IP,CPU,Ram,Ram use,Disk,Disk use,Trang thai VM,Trang thai Disk,Trang thai Ram,Disk_vz
27,1637,103.28.38.138,2,3072,34%,89G,5%,running,OK,OK,/vz1/private/1637
26,1636,103.28.38.163,2,3072,29%,89G,4%,running,OK,OK,/vz1/private/1636
25,1535,103.28.38.208,2,3000,27%,84G,9%,running,OK,OK,/vz6/private/1535
24,1533,103.28.38.180,2,3000,32%,84G,9%,running,OK,OK,/vz6/private/1533
23,1503,103.28.38.220,3,3072,64%,207G,31%,running,OK,OK,/vz2/private/1503
22,1443,103.28.38.21,2,3072,36%,89G,20%,running,OK,OK,/vz5/private/1443
21,1442,103.28.38.214,4,3000,38%,84G,10%,running,OK,OK,/vz1/private/1442
20,1402,103.28.38.224,2,3072,37%,89G,13%,running,OK,OK,/vz6/private/1402
19,1323,103.28.38.137,2,3000,52%,79G,23%,running,OK,OK,/vz6/private/1323
18,1320,103.28.38.212,4,8000,81%,207G,10%,running,OK,OK,/vz6/private/1320
17,1319,103.28.38.222,2,3072,41%,79G,15%,running,OK,OK,/vz6/private/1319
16,1312,103.28.38.211,2,3000,37%,79G,13%,running,OK,OK,/vz5/private/1312
15,1309,103.28.38.203,2,3072,52%,85G,38%,running,OK,OK,/vz5/private/1309
14,1307,103.28.38.215,2,3072,34%,89G,80%,running,OK,OK,/vz4/private/1307
13,1306,103.28.38.196,2,3000,44%,197G,7%,running,OK,OK,/vz4/private/1306
12,1304,103.28.38.202,2,3072,29%,89G,11%,running,OK,OK,/vz4/private/1304
11,1303,103.28.38.134,4,8000,85%,256G,7%,running,OK,OK,/vz4/private/1303
10,1302,103.28.38.174,2,3072,42%,89G,16%,running,OK,OK,/vz3/private/1302
9,1301,103.28.38.146,4,6000,93%,256G,10%,running,OK,FULL RAM,/vz3/private/1301
8,1300,103.28.38.83,4,6000,81%,256G,9%,running,OK,OK,/vz3/private/1300
7,1299,103.28.38.39,2,3072,32%,89G,12%,running,OK,OK,/vz1/private/1299
6,1298,103.28.38.155,2,3072,41%,128G,24%,running,OK,OK,/vz1/private/1298
5,1297,103.28.38.175,4,4096,25%,197G,8%,running,OK,OK,/vz3/private/1297
4,1296,103.28.38.216,2,3072,48%,89G,22%,running,OK,OK,/vz2/private/1296
3,1295,103.28.38.210,2,3072,36%,89G,26%,running,OK,OK,/vz2/private/1295
2,1293,103.28.38.80,2,3072,33%,128G,8%,running,OK,OK,/vz2/private/1293
1,1291,103.28.38.45,2,3072,41%,89G,11%,running,OK,OK,/vz2/private/1291
0,1287,103.28.38.164,2,3072,38%,89G,12%,running,OK,OK,/vz2/private/1287

In [46]:
# Get only every 2nd row (the even one)
stats[::2]

,CTID,IP,CPU,Ram,Ram use,Disk,Disk use,Trang thai VM,Trang thai Disk,Trang thai Ram,Disk_vz
0,1287,103.28.38.164,2,3072,38%,89G,12%,running,OK,OK,/vz2/private/1287
2,1293,103.28.38.80,2,3072,33%,128G,8%,running,OK,OK,/vz2/private/1293
4,1296,103.28.38.216,2,3072,48%,89G,22%,running,OK,OK,/vz2/private/1296
6,1298,103.28.38.155,2,3072,41%,128G,24%,running,OK,OK,/vz1/private/1298
8,1300,103.28.38.83,4,6000,81%,256G,9%,running,OK,OK,/vz3/private/1300
10,1302,103.28.38.174,2,3072,42%,89G,16%,running,OK,OK,/vz3/private/1302
12,1304,103.28.38.202,2,3072,29%,89G,11%,running,OK,OK,/vz4/private/1304
14,1307,103.28.38.215,2,3072,34%,89G,80%,running,OK,OK,/vz4/private/1307
16,1312,103.28.38.211,2,3000,37%,79G,13%,running,OK,OK,/vz5/private/1312
18,1320,103.28.38.212,4,8000,81%,207G,10%,running,OK,OK,/vz6/private/1320
20,1402,103.28.38.224,2,3072,37%,89G,13%,running,OK,OK,/vz6/private/1402
22,1443,103.28.38.21,2,3072,36%,89G,20%,running,OK,OK,/vz5/private/1443
24,1533,103.28.38.180,2,3000,32%,84G,9%,running,OK,OK,/vz6/private/1533
26,1636,103.28.38.163,2,3072,29%,89G,4%,running,OK,OK,/vz1/private/1636

In [53]:
# Part 2: Columns
stats.columns

Index(['CTID', 'IP', 'CPU', 'Ram', 'Ram use', 'Disk', 'Disk use',
       'Trang thai VM', 'Trang thai Disk', 'Trang thai Ram', 'Disk_vz'],
      dtype='object')

In [54]:
stats.head()

,CTID,IP,CPU,Ram,Ram use,Disk,Disk use,Trang thai VM,Trang thai Disk,Trang thai Ram,Disk_vz
0,1287,103.28.38.164,2,3072,38%,89G,12%,running,OK,OK,/vz2/private/1287
1,1291,103.28.38.45,2,3072,41%,89G,11%,running,OK,OK,/vz2/private/1291
2,1293,103.28.38.80,2,3072,33%,128G,8%,running,OK,OK,/vz2/private/1293
3,1295,103.28.38.210,2,3072,36%,89G,26%,running,OK,OK,/vz2/private/1295
4,1296,103.28.38.216,2,3072,48%,89G,22%,running,OK,OK,/vz2/private/1296

In [55]:
stats['IP']

0      103.28.38.164
1       103.28.38.45
2       103.28.38.80
3      103.28.38.210
4      103.28.38.216
5      103.28.38.175
6      103.28.38.155
7       103.28.38.39
8       103.28.38.83
9      103.28.38.146
10     103.28.38.174
11     103.28.38.134
12     103.28.38.202
13     103.28.38.196
14     103.28.38.215
15     103.28.38.203
16     103.28.38.211
17     103.28.38.222
18     103.28.38.212
19     103.28.38.137
20     103.28.38.224
21     103.28.38.214
22      103.28.38.21
23     103.28.38.220
24     103.28.38.180
25     103.28.38.208
26     103.28.38.163
27     103.28.38.138
Name: IP, dtype: object

In [56]:
stats['IP'].head(10)

0     103.28.38.164
1      103.28.38.45
2      103.28.38.80
3     103.28.38.210
4     103.28.38.216
5     103.28.38.175
6     103.28.38.155
7      103.28.38.39
8      103.28.38.83
9     103.28.38.146
Name: IP, dtype: object

In [58]:
stats[['IP', 'Disk use']].head(10)

               IP Disk use
0   103.28.38.164      12%
1    103.28.38.45      11%
2    103.28.38.80       8%
3   103.28.38.210      26%
4   103.28.38.216      22%
5   103.28.38.175       8%
6   103.28.38.155      24%
7    103.28.38.39      12%
8    103.28.38.83       9%
9   103.28.38.146      10%

In [59]:
stats[['Disk use','IP']].head(10)

  Disk use              IP
0      12%   103.28.38.164
1      11%    103.28.38.45
2       8%    103.28.38.80
3      26%   103.28.38.210
4      22%   103.28.38.216
5       8%   103.28.38.175
6      24%   103.28.38.155
7      12%    103.28.38.39
8       9%    103.28.38.83
9      10%   103.28.38.146

In [60]:
# Requires the name to be one word

In [61]:
stats.head()

,CTID,IP,CPU,Ram,Ram use,Disk,Disk use,Trang thai VM,Trang thai Disk,Trang thai Ram,Disk_vz
0,1287,103.28.38.164,2,3072,38%,89G,12%,running,OK,OK,/vz2/private/1287
1,1291,103.28.38.45,2,3072,41%,89G,11%,running,OK,OK,/vz2/private/1291
2,1293,103.28.38.80,2,3072,33%,128G,8%,running,OK,OK,/vz2/private/1293
3,1295,103.28.38.210,2,3072,36%,89G,26%,running,OK,OK,/vz2/private/1295
4,1296,103.28.38.216,2,3072,48%,89G,22%,running,OK,OK,/vz2/private/1296

In [66]:
stats.IP.head()

0     103.28.38.164
1      103.28.38.45
2      103.28.38.80
3     103.28.38.210
4     103.28.38.216
Name: IP, dtype: object

In [67]:
# Part 3: Combining the two

In [68]:
stats[4:8][['IP','Disk']]

               IP   Disk
4   103.28.38.216    89G
5   103.28.38.175   197G
6   103.28.38.155   128G
7    103.28.38.39    89G

In [69]:
stats[['IP','Disk']][4:8]

               IP   Disk
4   103.28.38.216    89G
5   103.28.38.175   197G
6   103.28.38.155   128G
7    103.28.38.39    89G

---

In [70]:
### Basic Operations with Dataframes

In [71]:
# Mathematical Operations:

In [83]:
stats.rename(columns={'Ram use': 'RamUse'}, inplace=True)

In [84]:
result = stats.Ram * stats['RamUse']

In [86]:
result

0      38% 38% 38% 38% 38% 38% 38% 38% 38% 38% 38% 3...
1      41% 41% 41% 41% 41% 41% 41% 41% 41% 41% 41% 4...
2      33% 33% 33% 33% 33% 33% 33% 33% 33% 33% 33% 3...
3      36% 36% 36% 36% 36% 36% 36% 36% 36% 36% 36% 3...
4      48% 48% 48% 48% 48% 48% 48% 48% 48% 48% 48% 4...
5      25% 25% 25% 25% 25% 25% 25% 25% 25% 25% 25% 2...
6      41% 41% 41% 41% 41% 41% 41% 41% 41% 41% 41% 4...
7      32% 32% 32% 32% 32% 32% 32% 32% 32% 32% 32% 3...
8      81% 81% 81% 81% 81% 81% 81% 81% 81% 81% 81% 8...
9      93% 93% 93% 93% 93% 93% 93% 93% 93% 93% 93% 9...
10     42% 42% 42% 42% 42% 42% 42% 42% 42% 42% 42% 4...
11     85% 85% 85% 85% 85% 85% 85% 85% 85% 85% 85% 8...
12     29% 29% 29% 29% 29% 29% 29% 29% 29% 29% 29% 2...
13     44% 44% 44% 44% 44% 44% 44% 44% 44% 44% 44% 4...
14     34% 34% 34% 34% 34% 34% 34% 34% 34% 34% 34% 3...
15     52% 52% 52% 52% 52% 52% 52% 52% 52% 52% 52% 5...
16     37% 37% 37% 37% 37% 37% 37% 37% 37% 37% 37% 3...
17     41% 41% 41% 41% 41% 41% 41% 41% 41% 41% 41% 4...
18     81% 81% 81% 81% 81% 81% 81% 81% 81% 81% 81% 8...
19     52% 52% 52% 52% 52% 52% 52% 52% 52% 52% 52% 5...
20     37% 37% 37% 37% 37% 37% 37% 37% 37% 37% 37% 3...
21     38% 38% 38% 38% 38% 38% 38% 38% 38% 38% 38% 3...
22     36% 36% 36% 36% 36% 36% 36% 36% 36% 36% 36% 3...
23     64% 64% 64% 64% 64% 64% 64% 64% 64% 64% 64% 6...
24     32% 32% 32% 32% 32% 32% 32% 32% 32% 32% 32% 3...
25     27% 27% 27% 27% 27% 27% 27% 27% 27% 27% 27% 2...
26     29% 29% 29% 29% 29% 29% 29% 29% 29% 29% 29% 2...
27     34% 34% 34% 34% 34% 34% 34% 34% 34% 34% 34% 3...
dtype: object